export const currSkuData_407754 = {
  "itemNumber": "40775",
  "uomlist": [
    "TB"
  ],
  "productNumber": "OSIQU405",
  "hoverAttributes": null,
  "currentUOM": "TB",
  "skuShortDesc": null,
  "itemImage": "/images/large/40775_default_hero.jpg",
  "swatchImage": "/images/large/40775_default_swatch.jpg",
  "thumbImage": "/images/large/40775_default_thumb.jpg",
  "manufactureNumber": "QUAD405",
  "auxiliaryImages": null,
  "variations": {
    "color": [
      "Country Beige(405)",
      "Sandalwood(405)",
      "Autumn Beige(405)",
      "Beige(405)",
      "Almond(405)",
      "Wicker(405)",
      "Maple(405)",
      "Warm Sandalwood(405)",
      "Walnut(405)",
      "Sand/Sandstone(405)",
      "Manor White(405)",
      "Martin Beige(405)",
      "Sand Beige(405)",
      "Harvey Almond(405)",
      "Tan(405)",
      "Hayfield Beige(405)",
      "Summer Suede(405)",
      "Sandstone(405)",
      "Beige Coated(405)",
      "Cape Cod Grey(405)",
      "Tripoli Tan(405)",
      "Sandy Tan(405)"
    ],
    "MFG": [
      "Best Line Building Products",
      "Quality Edge",
      "Acadia Windows & Doors",
      "Wintech Windows",
      "Provia Siding",
      "ViWinTech",
      "Mitten",
      "Amcraft",
      "Olympic/PPG Cape Cod Finished Wood Siding",
      "Norandex PVC Trim Coil",
      "Crane",
      "Napco",
      "Lester Buildings",
      "New Era Windows",
      "Harvey Building Products",
      "Georgia Pacific",
      "Daymond",
      "Exterior Portfolio",
      "Mastic by Plygem",
      "Atrium",
      "Heartland",
      "Beechworth Windows",
      "Stylecrest",
      "Variform",
      "Finestone",
      "Alliance Windows",
      "Midway Windows",
      "Norandex Windows & Doors: Extreme & Viewpoint",
      "Rollex",
      "Olympic",
      "Truewall",
      "Mastershield",
      "Fleetwood Windows & Doors",
      "Weathershield Windows & Doors",
      "Alsco",
      "Polaris",
      "South Seneca Vinyl Windows",
      "Seaway Manufacturing",
      "Peachtree"
    ]
  },
  "heroImages": [
    {
      "image": "/images/large/40775_default_hero.jpg"
    }
  ]
} 